Enable benchmarks again (#104)
Signed-off-by: Timo <38291523+lovetodream@users.noreply.github.com>

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -3,116 +3,123 @@ name: Benchmark PR vs main
 on:
   workflow_dispatch:
   pull_request:
-    branches: [main]
+    branches:
+      - main
+    paths:
+      - "**.swift"
+      - "**.yml"
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
+  group: ${{ github.workflow }}-${{ github.ref }}-benchmark
   cancel-in-progress: true
+
+env:
+  ENABLE_ORACLE_BENCHMARKS: true
 
 jobs:
   benchmark-delta:
     runs-on: ${{ matrix.os }}
+    timeout-minutes: 60
     continue-on-error: true
     permissions:
       issues: write
       pull-requests: write
+      contents: read
 
     strategy:
       matrix:
-        os: [[Linux, benchmarks, self-hosted]]
+        os: [ubuntu-latest]
+        image: ["swift:6.1"]
 
-    services:
-      oracle:
-        image: gvenzl/oracle-free:23
-        env:
-          ORACLE_PASSWORD: my_very_secure_password
-          APP_USER: my_user
-          APP_USER_PASSWORD: my_password
-        ports:
-          - 1521:1521
-        options: >-
-          --health-cmd healthcheck.sh
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 10
-
-    env:
-      ENABLE_ORACLE_BENCHMARKS: 1
+    container:
+      image: ${{ matrix.image }}
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: Homebrew Mac
-        if: ${{ runner.os == 'Macos' }}
+      - name: Install jemalloc
         run: |
-          echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
-          brew install jemalloc
+          apt-get -q update
+          apt-get install -y libjemalloc-dev
 
-      - name: Git URL token override and misc
+      # https://github.com/actions/checkout/issues/766
+      - name: Mark the workspace as safe
+        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
+
+      - name: Miscellaneous
         run: |
           [ -d Benchmarks ] && echo "hasBenchmark=1" >> $GITHUB_ENV
-          echo "/opt/homebrew/bin:/usr/local/bin:/home/actions/.local/bin" >> $GITHUB_PATH
+          echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
       - name: Run benchmarks for PR branch
         if: ${{ env.hasBenchmark == '1' }}
         run: |
-          swift package --disable-sandbox --allow-writing-to-directory .benchmarkBaselines/ benchmark baseline update pull_request --no-progress --quiet
-        env:
-          ORA_HOSTNAME: 127.0.0.1
-          ORA_PORT: 1521
-          ORA_SERVICE_NAME: FREEPDB1
-          ORA_USERNAME: my_user
-          ORA_PASSWORD: my_password
-      - name: Switch to branch 'main'
-        if: ${{ env.hasBenchmark == '1' }}
+          swift package --allow-writing-to-directory .benchmarkBaselines/ benchmark baseline update pull_request
+      - name: Checkout main
         run: |
-          git stash
           git checkout main
       - name: Run benchmarks for branch 'main'
         if: ${{ env.hasBenchmark == '1' }}
         run: |
-          swift package --disable-sandbox --allow-writing-to-directory .benchmarkBaselines/ benchmark baseline update main --no-progress --quiet
-        env:
-          ORA_HOSTNAME: 127.0.0.1
-          ORA_PORT: 1521
-          ORA_SERVICE_NAME: FREEPDB1
-          ORA_USERNAME: my_user
-          ORA_PASSWORD: my_password
+          swift package --allow-writing-to-directory .benchmarkBaselines/ benchmark baseline update main
       - name: Compare PR and main
         if: ${{ env.hasBenchmark == '1' }}
         id: benchmark
         run: |
-          echo '## Summary' >> $GITHUB_STEP_SUMMARY
-          echo $(date) >> $GITHUB_STEP_SUMMARY
-          echo "exitStatus=1" >> $GITHUB_ENV
-          swift package benchmark baseline check main pull_request --format markdown >> $GITHUB_STEP_SUMMARY
-          echo '---' >> $GITHUB_STEP_SUMMARY
-          swift package benchmark baseline compare main pull_request --no-progress --quiet --format markdown >> $GITHUB_STEP_SUMMARY
-          echo "exitStatus=0" >> $GITHUB_ENV
-        continue-on-error: true
-      - if: ${{ env.exitStatus == '0' }}
-        name: Pull request comment text success
-        id: prtestsuccess
+          set +e
+          # if we had access to fd 3 we could do this in one call eg { var=$(cmd 3>&2 2>&1 1>&3); }  2>&1
+          # but unfortunately we don't so we have to run the baseline check twice once to extract stdout
+          # and once to extract stderr
+          BENCHMARK_STDERR=$(swift package benchmark baseline check main pull_request 2>&1)
+          echo "exit-status=$?" >> $GITHUB_OUTPUT
+          echo "benchmark-error=$(echo -e "$BENCHMARK_STDERR" | grep -e "^error: .*" | tail -n 1 | cut -c 8-)" >> $GITHUB_OUTPUT
+          set -e
+      - name: Pull request comment text
+        id: benchmark-comment
         run: |
-          echo 'PRTEST<<EOF' >> $GITHUB_ENV
-          echo "[Pull request benchmark comparison [${{ matrix.os }}] with 'main' run at $(date -Iseconds)](https://github.com/lovetodream/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }})" >> $GITHUB_ENV
-          echo 'EOF' >> $GITHUB_ENV
-      - if: ${{ env.exitStatus == '1' }}
-        name: Pull request comment text failure
-        id: prtestfailure
-        run: |
-          echo 'PRTEST<<EOF' >> $GITHUB_ENV
-          echo "[Pull request benchmark comparison [${{ matrix.os }}] with 'main' run at $(date -Iseconds)](https://github.com/lovetodream/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }})" >> $GITHUB_ENV
-          echo "_Pull request had performance regressions_" >> $GITHUB_ENV
-          echo 'EOF' >> $GITHUB_ENV
+          EXIT_CODE='${{steps.benchmark.outputs.exit-status}}'
+
+          case "${EXIT_CODE}" in
+            0)
+              echo "_✅ Pull request no significant performance differences ✅_" >> comment.md
+              echo "exitStatus=0" >> $GITHUB_ENV
+              ;;
+            *)
+              # Get error string from benchmark output
+              BENCHMARK_ERROR='${{steps.benchmark.outputs.benchmark-error}}'
+              case "${BENCHMARK_ERROR}" in
+                "benchmarkThresholdRegression")
+                  echo "_❌ Pull request has performance regressions ❌_" >> comment.md
+                  echo "exitStatus=1" >> $GITHUB_ENV
+                  ;;
+                "benchmarkThresholdImprovement")
+                  echo "_✅ Pull request has performance improvements ✅_" >> comment.md
+                  echo "exitStatus=0" >> $GITHUB_ENV
+                  ;;
+                *)
+                  echo "_❌ Benchmark comparison failed with error $BENCHMARK_ERROR ❌_" >> comment.md
+                  echo "exitStatus=1" >> $GITHUB_ENV
+                  ;;
+              esac
+              ;;
+          esac
+
+          set +e
+          echo "<details><summary>Summary</summary>" >> comment.md
+          swift package benchmark baseline check main pull_request --format markdown >> comment.md
+          echo "</details><details><summary>Full Benchmark Comparison</summary>" >> comment.md
+          swift package benchmark baseline compare main pull_request --no-progress --quiet --format markdown >> comment.md
+          echo "</details>" >> comment.md
+          set -e
+
       - name: Comment PR
         if: ${{ env.hasBenchmark == '1' }}
-        uses: thollander/actions-comment-pull-request@v2
+        uses: thollander/actions-comment-pull-request@v3
         with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          message: ${{ env.PRTEST }}
-          comment_includes: "Pull request benchmark comparison [${{ matrix.os }}] with"
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          file-path: comment.md
+          comment-tag: benchmark
       - name: Exit with correct status
         run: |
-          exit ${{ env.exitStatus }}
+          exit ${{env.exitStatus}}
